### ISSUE TITLE
.main-wrap minxin question..

### ISSUE THREAD

**Issue by JPOak** [olefredrik/FoundationPress#1146]
I don't think this is a bug, not sure, but little things like this drive me nuts and I am wondering if anybody else has run into this....  For the full-width template shouldn't the output of the  mixin FP uses equal the same as the below?

However, there are extra margins on our usage as a mixin on the grid. I tried to add grid-margin-x , but the same.

```
<div class="grid-container">
  <div class="grid-x">
    <div class="cell medium-12"><p>cell</p></div>
  </div>
</div>
```

**Comment by colin-marshall** [comment]
Looks like by default the `xy-cell` mixin has margin gutters. That's kind of confusing since when not using the mixin you have to add the `grid-margin-x` class in order to get margins. I guess it has to be setup this way in order to allow for the option to have padding or margin gutters.

```scss
/// Creates a cell for your grid.
///
/// @param {Keyword|Number} $size [full] - The size of your cell. Can be `full` (default) for 100% width, `auto` to use up available space and `shrink` to use up only required space.
/// @param {Boolean} $gutter-output [true] - Whether or not to output gutters
/// @param {Number|Map} $gutters [$grid-margin-gutters] - Map or single value for gutters.
/// @param {Keyword} $gutter-type [margin] - Map or single value for gutters.
/// @param {List} $gutter-position [right left] - The position to apply gutters to. Accepts `top`, `bottom`, `left`, `right` in any combination.
/// @param {String} $breakpoint [null] - The name of the breakpoint size in your gutters map to get the size from. If using with the `breakpoint()` mixin this will be set automatically unless manually entered.
/// @param {Boolean} $vertical [false] - Set to true to output vertical (height) styles rather than widths.
@mixin xy-cell(
  $size: full,
  $gutter-output: true,
  $gutters: $grid-margin-gutters,
  $gutter-type: margin,
  $gutter-position: right left,
  $breakpoint: null,
  $vertical: false
)
```

In FP, even if you set `$gutter-output` to `false` for `.full-width`, you'll still get gutters (larger ones) because it falls back to the margins from the non full-width layout because both templates use the `.main-content` class.

We should probably just have a `.main-content-full-width` class and a `.main-content` class instead of putting a `.full width` class on the `.main-wrap` to prevent overrides.
