### ISSUE TITLE
xy-grid, section and footer widgets

### ISSUE THREAD

**Issue by jtmcgraw** [olefredrik/FoundationPress#1180]
Footer widgets weren't expanding to full width at medium and small breakpoints.

I added grid-x to `<footer class="footer">` in footer.php --- didn't work
I replaced large-4 column with large-4 cell in `<section class="">` in /library/widget-areas.php ---  still didn't work
Wrapped `<section>` in `<div class="large-4 cell">` in /library/widgert-areas.php --- working for me, but maybe not ideal...

**Comment by colin-marshall** [comment]
@jtmcgraw thanks for the report. This is related to #1151 and #1159.

Currently the footer is like this:

```php
<div class="footer-container">
    <footer class="footer">
        <?php dynamic_sidebar( 'footer-widgets' ); ?>
    </footer>
</div>
```

```scss
.footer-container {
  margin: 0 auto;
  border-top: 1px solid $medium-gray;
  margin-top: rem-calc(60);
}

.footer {
  @include xy-grid-container;
  @include xy-grid;
  padding: rem-calc(30) 0;

  section {
    @include xy-cell(auto);
  }

  ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
  }
}
```

I propose we change it to this:

```php
<footer class="footer-container">
    <div class="footer-grid">
        <?php dynamic_sidebar( 'footer-widgets' ); ?>
    </div>
</footer>
```

```scss
.footer-container {
  @include xy-grid-container;
  margin: 0 auto;
  border-top: 1px solid $medium-gray;
  margin-top: rem-calc(60);
}

.footer-grid {
  @include xy-grid;
  padding: rem-calc(30) 0;

  section {
    @include xy-cell(auto);
  }

  ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
  }
}
```

What do you guys think?
