### ISSUE TITLE
Changing breakpoints for Mobile Menu not working

### ISSUE THREAD

**Issue by pcross1986** [olefredrik/FoundationPress#1240]
I thought I've done this before, but it seems to not be working. Maybe you could explain to me if I am missing something or doing something wrong?

My objective is to simply show desktop navigation for large devices only and have the mobile menu and menu toggle button show for the small and medium devices.

**Version info located in style.css file:**
Theme Name:         FoundationPress
Theme URI:          http://foundationpress.olefredrik.com
Github Theme URI:   https://github.com/olefredrik/FoundationPress
Description:        FoundationPress is a WordPress starter theme based on Foundation 6 by Zurb
Version:            2.7.1
Author:             Ole Fredrik Lie
Author URI:         http://olefredrik.com/

License:            MIT License
License URI:        http://www.opensource.org/licenses/mit-license.php

**My markup:**

```html
<header id="masthead" class="site-header" role="banner">
		
		<div class="title-bar <?php if(is_front_page()) { echo 'title-bar-shadow'; } ?>" data-responsive-toggle="site-navigation">
			<div class="title-bar-left">
				<div class="title-bar-title">
					<a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home"><img src="<?php echo get_template_directory_uri(); ?>/assets/images/auto_dealer_logo.png" style="width: 140px;" /></a>
				</div>
			</div>
			<div class="title-bar-right">
				<button class="menu-icon" type="button" data-toggle="mobile-menu"></button>
			</div>
		</div>

		<div class="row">
			<div class="columns large-12">
				<nav id="site-navigation" class="main-navigation top-bar" role="navigation">
					<div class="top-bar-left">
						<ul class="menu">
							<li class="home"><a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home" class="home-title"><img src="<?php echo get_template_directory_uri(); ?>/assets/images/auto_dealer_logo.png" style="width: 150px;" /></a></li>
						</ul>
					</div>
					<div class="top-bar-right">
						<?php foundationpress_top_bar_r(); ?>

						<?php if ( ! get_theme_mod( 'wpt_mobile_menu_layout' ) || get_theme_mod( 'wpt_mobile_menu_layout' ) == 'topbar' ) : ?>
							<?php get_template_part( 'template-parts/mobile-top-bar' ); ?>
						<?php endif; ?>
					</div>
				</nav>
			</div>
		</div>
	</header>
```

**My sass/css from navigation.scss**

```scss
/ Navigation breakpoints
.desktop-menu, .top-bar-left {
  @include show-for(large);
}

#mobile-menu, .title-bar {
  @include hide-for(large);
}

.title-bar {
  z-index: 5;
  position: relative;
  padding: 1.25rem 1.25rem 1.25rem .625rem;
  background-image: url(../images/title-bar-bg.png);
  background-position: left top;
  background-size: contain;
  background-repeat: repeat-x;
}

.title-bar-shadow {
  box-shadow: 0 3px 25px rgba(0,0,0,0.5);
}

.title-bar .menu-icon {
  margin-right: 0.5rem;
  margin-top: 0.15rem;

  &:after {
    height: 1px;
  }
}
```

**Comment by pcross1986** [comment]
Hello?

**Comment by AmyGail** [comment]
I got stuck on this too.
I know I've made it work in earlier versions, but there's obviously something I'm missing in the latest version.
If someone can help @pcross1986 , they'll help me too.
Thanks!

**Comment by pcross1986** [comment]
@amygail Yeah I wish I knew the answer. Looks like I will resort to using some media queries with classes. I cant wait a week for a simple question, Ive got to get a project finished. I wish it worked how it was intended though.

**Comment by colin-marshall** [comment]
What happens when you change to medium? Does it still just do the large breakpoint like nothing changed?

You're using an older version of FP, but you could try changing your scss to the following:

```scss
.desktop-menu, .top-bar-left {
  @include breakpoint(medium down) {
    display: none;
  }
}

#mobile-menu, .title-bar {
  @include breakpoint(large) {
    display: none;
  }
}

```
