### ISSUE TITLE
editor.scss error with .wp-block class

### ISSUE THREAD

**Issue by Jeremy-Bolella** [olefredrik/FoundationPress#1388]
With FoundationPress 2.10.5 and 2.10.6 there's an error in _editor.scss with the .wp-block class. It seems like this isn't effecting how gutenberg works but the class is being exported and is invalid.
**_editor.scss:**
```css
/** === Content Width === */
.wp-block {
	width: calc(100vw - (2 * 10));
	@each $breakpoint, $size in $grid-margin-gutters {

		@include breakpoint($breakpoint) {
			width: calc(100vw - ($size));
		}

	}
}
```
**editor.css**
```css
/** === Content Width === */
.wp-block {
  width: calc(100vw - (2 * 10));
  width: calc(100vw - ($size)); }
  @media print, screen and (min-width: 40em) {
    .wp-block {
      width: calc(100vw - ($size)); } }
```
