### ISSUE TITLE
Simplify _icon.scss a bit?

### ISSUE THREAD

**Issue by imsadhappy** [olefredrik/FoundationPress#143]
Hi. There is a question I have concerning _icons.scss.

Why not use CSS ```[attribute^=value]``` selector, rather than enumerate all the ```.fi-[icon]:before``` (from line 18 to line 310)? Surely, this is how Foundation does it, but can it be more efficient?

Like this:
```css
[class^="fi-"]:before {
font-family: "foundation-icons";
font-style: normal;
font-weight: normal;
font-variant: normal;
text-transform: none;
line-height: 1;
-webkit-font-smoothing: antialiased;
display: inline-block;
text-decoration: inherit;
}
```
