### ISSUE TITLE
Top Bar breakpoint

### ISSUE THREAD

**Issue by dioogbento** [olefredrik/FoundationPress#355]
Deleting line 57 in the custom settings sass file (in case one wants to stick with the default breakpoint)

```sass
$topbar-breakpoint: em-calc(820);
```
outputs css to

```css
@media only screen and (min-width: 40.0625em0.0625em){.tab-bar{display:none}}
```
Line 21 in the topbar sass file should then be:

```sass
@media only screen and (min-width: $topbar-breakpoint) {
  .tab-bar { display: none; }
}
```
