### ISSUE TITLE
How to change topbar height?

### ISSUE THREAD

**Issue by jdfweb** [olefredrik/FoundationPress#647]
Two part question:

Question #1:

In F5, this was super easy! There was a specific SASS variable to change the topbar height.

Now in F6, it looks like there's not even half of the variables present anymore. I'm not exactly sure how to change the topbar height with SASS now!

I checked the _topbar.scss file, and there's no SASS variables in there either.

Is there an option in FoundationPress? 

Also, are there any other topbar options anywhere else? F6 seems so sparse and it's making things more difficult than F5.

Question #2:

How exactly do you contain the navigation to grid? I've tried "contain-to-grid" in a couple places and it doesn't work!

Any help would be appreciated!

**Comment by colin-marshall** [comment]
Check out this: http://zurb.com/university/lessons/how-to-re-create-top-bar-with-foundation-6

To mess with the height you only need to change the `top-bar` class's padding. To "contain-to-gird" just wrap everything inside of the `top-bar` div with a `row` div.

**Comment by jdfweb** [comment]
Thank you!

**Comment by GarySwift** [comment]
Although this issue is closed I'm going add how I achieve this through scss. 

```scss
$topbar-height: 35px;
.top-bar .menu a { 
	height: $topbar-height;
	line-height: $topbar-height;
}
.top-bar .menu > li:not(.menu-text) > a {
    padding: 0 1rem;
}
```
Hopefully this can help someone who needs a quick fix. Just increase (or decrease) the `$topbar-height` variable to whatever height you want.
