### ISSUE TITLE
Dropdown Menu Arrows

### ISSUE THREAD

**Issue by colin-marshall** [olefredrik/FoundationPress#752]
When we did the 6.2 update, I had to move the line below outside of `.top-bar` to be able to keep arrows on 2nd level list items. This will effect all dropdowns that a developer would create in their theme which is probably not what we want. We need to figure out a way so that this rule is only applied to the `.top-bar` menu.

```scss
.dropdown.menu > li.is-dropdown-submenu-parent > a::after { display: none; }
```

https://github.com/olefredrik/FoundationPress/blob/master/assets/scss/modules/_navigation.scss#L63
